version: '3.8'
services:
  web:
    build: .
    ports:
      - '5000:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - db
      - redis
    command: gunicorn "Eyes-of-an-Addict.app:create_app()" --workers 2 --bind 0.0.0.0:8000

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb

  redis:
    image: redis:7
